const FIRST_INDEX = 0;
const LAST_INDEX_IS_LENGTH_MINUS_ONE = -1;

const LENGTH_OF_EMPTY_LIST = 0;
const SIZE_OF_EMPTY_SET = 0;

const NOT_INCREMENT = 0;
const INCREMENT_ONE = 1;
const DECREMENT_ONE = -1;

export {
  DECREMENT_ONE,
  FIRST_INDEX,
  INCREMENT_ONE,
  LAST_INDEX_IS_LENGTH_MINUS_ONE,
  LENGTH_OF_EMPTY_LIST,
  NOT_INCREMENT,
  SIZE_OF_EMPTY_SET,
};
