@startuml play
title Play game
!pragma useVerticalIf on
skinparam ConditionEndStyle hline

start

:Print initial state of the game.;

repeat

  partition Turn {

  :Echo `Player X's turn.`;
  :Print valid moves.;

  if(Player X is a human?) then (yes)
    :Read move.;
    while (Player X's move is valid?) is (no)
      :Echo `Invalid move.`;
    endwhile (yes)
  else (no)
    :Predict the best move.;
  endif


  :Play move.;
  :Print updated state of the game.;
}

backward:Change current player to the next one.;
repeat while (Player X wins?) is (no)
-> yes;

:Print the points of each player.;

stop

@enduml
