import { recordOfSnowballGamesWithData } from "../SnowballGame.test/records.js";
import {
  recordOfSnowballMovesWithDataAndIndex,
  type SnowballMoveWithDataAndIndex,
} from "../SnowballMove.test/indexedRecords.js";
import { type SnowballMoveWithData } from "../SnowballMove.test/setup.js";
import { recordOfSnowballPlayersWithDataAndIndex } from "../SnowballPlayer.test/indexedRecords.js";
import { recordOfSnowballScoresWithData } from "../SnowballScore.test/records.js";
import {
  indexedSnowballSlotsWithDataInWhichAllSlotsAreEmpty,
  indexedSnowballSlotsWithDataInWhichSlotR0C0IsFilledByAlice,
  indexedSnowballSlotsWithDataInWhichSlotsR0C0ToR3C3AndR4C0AndR4C2AreFilledByAliceAndSlotsR0C4ToR3C7AndR3C8AreFilledByBruno,
  indexedSnowballSlotsWithDataInWhichSlotsR0C0ToR3C3AndR4C0AreFilledByAliceAndSlotsR0C4ToR3C7AndR3C8AreFilledByBruno,
  indexedSnowballSlotsWithDataInWhichSlotsR0C0ToR4C4AndR5C5AreFilledByAliceAndSlotsR8C4AndR6C5ToR8C6AndR0C7ToR8C8AreFilledByBruno,
} from "../SnowballSlot.test/indexedRecords.js";
import {
  createRecordOfSnowballStatesWithData,
  type RecordOfRequiredParamsOfSnowballStates,
} from "./setup.js";

const constructTupleForMove = ({
  moveWithDataAndIndex,
}: {
  moveWithDataAndIndex: SnowballMoveWithDataAndIndex;
}): [number, SnowballMoveWithData] => [
  moveWithDataAndIndex.indexOfMove,
  moveWithDataAndIndex.moveWithData,
];

const recordOfRequiredParamsOfSnowballStates = {
  allSlotsAreEmptyAndAliceHas0PointsAndBrunoHas0PointsAndAliceIsTheCurrentPlayer:
    {
      gameWithData: recordOfSnowballGamesWithData.snowballWith9RowsAnd9Columns,
      isFinal: false,
      nextPlayerWithDataAndIndex: recordOfSnowballPlayersWithDataAndIndex.bruno,
      playerWithDataAndIndex: recordOfSnowballPlayersWithDataAndIndex.alice,
      scoreWithData:
        recordOfSnowballScoresWithData.aliceWith0PointsAndBrunoWith0Points,
      slotsWithData: indexedSnowballSlotsWithDataInWhichAllSlotsAreEmpty,
      validMovesWithData: new Map([
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfWest,
        }),
      ]),
    },
  slotR0C0IsFilledByAliceAndAliceHas0PointsAndBrunoHas0PointsAndBrunoIsTheCurrentPlayer:
    {
      gameWithData: recordOfSnowballGamesWithData.snowballWith9RowsAnd9Columns,
      isFinal: false,
      nextPlayerWithDataAndIndex: recordOfSnowballPlayersWithDataAndIndex.alice,
      playerWithDataAndIndex: recordOfSnowballPlayersWithDataAndIndex.bruno,
      scoreWithData:
        recordOfSnowballScoresWithData.aliceWith0PointsAndBrunoWith0Points,
      slotsWithData: indexedSnowballSlotsWithDataInWhichSlotR0C0IsFilledByAlice,
      validMovesWithData: new Map([
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfWest,
        }),
      ]),
    },
  slotsR0C0ToR3C3AndR4C0AndR4C2AreFilledByAliceAndSlotsR0C4ToR3C7AndR3C8AreFilledByBrunoAndAliceHas0PointsAndBrunoHas0PointsAndBrunoIsTheCurrentPlayer:
    {
      gameWithData: recordOfSnowballGamesWithData.snowballWith9RowsAnd9Columns,
      isFinal: true,
      nextPlayerWithDataAndIndex: recordOfSnowballPlayersWithDataAndIndex.alice,
      playerWithDataAndIndex: recordOfSnowballPlayersWithDataAndIndex.bruno,
      scoreWithData:
        recordOfSnowballScoresWithData.aliceWith15PointsAndBrunoWith14Points,
      slotsWithData:
        indexedSnowballSlotsWithDataInWhichSlotsR0C0ToR3C3AndR4C0AndR4C2AreFilledByAliceAndSlotsR0C4ToR3C7AndR3C8AreFilledByBruno,
      validMovesWithData: new Map([
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfSouthwest,
        }),
      ]),
    },
  slotsR0C0ToR3C3AndR4C0AreFilledByAliceAndSlotsR0C4ToR3C7AndR3C8AreFilledByBrunoAndAliceHas0PointsAndBrunoHas0PointsAndAliceIsTheCurrentPlayer:
    {
      gameWithData: recordOfSnowballGamesWithData.snowballWith9RowsAnd9Columns,
      isFinal: false,
      nextPlayerWithDataAndIndex: recordOfSnowballPlayersWithDataAndIndex.bruno,
      playerWithDataAndIndex: recordOfSnowballPlayersWithDataAndIndex.alice,
      scoreWithData:
        recordOfSnowballScoresWithData.aliceWith14PointsAndBrunoWith14Points,
      slotsWithData:
        indexedSnowballSlotsWithDataInWhichSlotsR0C0ToR3C3AndR4C0AreFilledByAliceAndSlotsR0C4ToR3C7AndR3C8AreFilledByBruno,
      validMovesWithData: new Map([
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfSouthwest,
        }),
      ]),
    },
  slotsR0C0ToR4C4AndR5C5AreFilledByAliceAndSlotsR8C4AndR6C5ToR8C6AndR0C7ToR8C8AreFilledByBrunoAndAliceHas0PointsAndBrunoHas0PointsAndBrunoIsTheCurrentPlayer:
    {
      gameWithData: recordOfSnowballGamesWithData.snowballWith9RowsAnd9Columns,
      isFinal: true,
      nextPlayerWithDataAndIndex: recordOfSnowballPlayersWithDataAndIndex.alice,
      playerWithDataAndIndex: recordOfSnowballPlayersWithDataAndIndex.bruno,
      scoreWithData:
        recordOfSnowballScoresWithData.aliceWith38PointsAndBrunoWith26Points,
      slotsWithData:
        indexedSnowballSlotsWithDataInWhichSlotsR0C0ToR4C4AndR5C5AreFilledByAliceAndSlotsR8C4AndR6C5ToR8C6AndR0C7ToR8C8AreFilledByBruno,
      validMovesWithData: new Map([
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfSouthwest,
        }),
      ]),
    },
} as const satisfies RecordOfRequiredParamsOfSnowballStates;

const recordOfSnowballStatesWithData = createRecordOfSnowballStatesWithData({
  recordOfRequiredParamsOfStates: recordOfRequiredParamsOfSnowballStates,
});

export type { RecordOfRequiredParamsOfSnowballStates };
export {
  recordOfRequiredParamsOfSnowballStates,
  recordOfSnowballStatesWithData,
};
