import type {
  RecordOfSlotsWithDataAndIndex,
  SlotWithDataAndIndex,
} from "@repo/game/Slot.test/setup.js";

import type { TicTacToeSlot } from "../Slot.js";
import type {
  RecordOfRequiredParamsOfTicTacToeSlots,
  RecordOfTicTacToeSlotsWithData,
  RequiredParamsOfTicTacToeSlot,
  TicTacToeSlotWithData,
} from "./setup.js";

import {
  recordOfTicTacToeSlotsWithDataInWhichAllSlotsAreEmpty,
  recordOfTicTacToeSlotsWithDataInWhichSlotR0C0IsFilledByAlice,
  recordOfTicTacToeSlotsWithDataInWhichSlotR0C1IsFilledByAlice,
  recordOfTicTacToeSlotsWithDataInWhichSlotR0C2IsFilledByAlice,
  recordOfTicTacToeSlotsWithDataInWhichSlotR1C0IsFilledByAlice,
  recordOfTicTacToeSlotsWithDataInWhichSlotR1C1IsFilledByAlice,
  recordOfTicTacToeSlotsWithDataInWhichSlotR1C2IsFilledByAlice,
  recordOfTicTacToeSlotsWithDataInWhichSlotR2C0IsFilledByAlice,
  recordOfTicTacToeSlotsWithDataInWhichSlotR2C1IsFilledByAlice,
  recordOfTicTacToeSlotsWithDataInWhichSlotR2C2IsFilledByAlice,
  recordOfTicTacToeSlotsWithDataInWhichSlotsR0C0AndR0C1AndR1C0AreFilledByAliceAndR0C2AndR1C1AreFilledByBruno,
  recordOfTicTacToeSlotsWithDataInWhichSlotsR0C0AndR0C1AndR1C2AndR2C0AreFilledByAliceAndR0C2AndR1C0AndR1C1AreFilledByBruno,
  recordOfTicTacToeSlotsWithDataInWhichSlotsR0C0AndR0C1AreFilledByAliceAndR1C1IsFilledByBruno,
  recordOfTicTacToeSlotsWithDataInWhichSlotsR0C0AndR0C1AreFilledByAliceAndR2C0IsFilledByBruno,
  recordOfTicTacToeSlotsWithDataInWhichSlotsR0C0AndR0C2AndR1C1AndR1C2AndR2C1AreFilledByAliceAndR0C1AndR1C0AndR2C0AndR2C2AreFilledByBruno,
  recordOfTicTacToeSlotsWithDataInWhichSlotsR0C0AndR0C2AndR1C1AndR2C1AndR2C2AreFilledByAliceAndR0C1AndR1C0AndR1C2AndR2C0AreFilledByBruno,
  recordOfTicTacToeSlotsWithDataInWhichSlotsR0C0AndR0C2AndR1C1AndR2C1AreFilledByAliceAndR0C1AndR1C0AndR1C2AndR2C0AreFilledByBruno,
  recordOfTicTacToeSlotsWithDataInWhichSlotsR0C0AndR1C0AreFilledByAliceAndR0C1IsFilledByBruno,
  recordOfTicTacToeSlotsWithDataInWhichSlotsR1C0AndR1C2AndR2C0AreFilledByAliceAndR0C0AndR1C1AreFilledByBruno,
} from "./records.js";

type KeysOfSlotsInOrder<
  GenericRecordOfRequiredParamsOfTicTacToeSlots extends
    RecordOfRequiredParamsOfTicTacToeSlots,
> = (keyof GenericRecordOfRequiredParamsOfTicTacToeSlots)[];

type RecordOfTicTacToeSlotsWithDataAndIndex<
  GenericRecordOfRequiredParamsOfTicTacToeSlots extends
    RecordOfRequiredParamsOfTicTacToeSlots,
> = RecordOfSlotsWithDataAndIndex<
  TicTacToeSlot,
  RequiredParamsOfTicTacToeSlot,
  GenericRecordOfRequiredParamsOfTicTacToeSlots,
  TicTacToeSlotWithData
>;

type TicTacToeSlotWithDataAndIndex = SlotWithDataAndIndex<
  TicTacToeSlot,
  RequiredParamsOfTicTacToeSlot,
  TicTacToeSlotWithData
>;

const createIndexedTicTacToeSlotsWithData = <
  GenericRecordOfRequiredParamsOfTicTacToeSlots extends
    RecordOfRequiredParamsOfTicTacToeSlots,
>({
  keysOfTicTacToeSlotsInOrder,
  ticTacToeSlotsWithData,
}: {
  keysOfTicTacToeSlotsInOrder: KeysOfSlotsInOrder<GenericRecordOfRequiredParamsOfTicTacToeSlots>;
  ticTacToeSlotsWithData: RecordOfTicTacToeSlotsWithData<GenericRecordOfRequiredParamsOfTicTacToeSlots>;
}) => {
  const recordOfTicTacToeSlotsWithDataAndIndex =
    // eslint-disable-next-line @typescript-eslint/no-unsafe-type-assertion
    {} as RecordOfTicTacToeSlotsWithDataAndIndex<GenericRecordOfRequiredParamsOfTicTacToeSlots>;
  const indexedTicTacToeSlotsWithData: (typeof ticTacToeSlotsWithData)[keyof typeof ticTacToeSlotsWithData][] =
    [];

  keysOfTicTacToeSlotsInOrder.forEach((keyOfSlot, indexOfSlot) => {
    const slotWithData = ticTacToeSlotsWithData[keyOfSlot];
    recordOfTicTacToeSlotsWithDataAndIndex[keyOfSlot] = {
      indexOfSlot,
      slotWithData,
    } as RecordOfTicTacToeSlotsWithDataAndIndex<GenericRecordOfRequiredParamsOfTicTacToeSlots>[typeof keyOfSlot];
    indexedTicTacToeSlotsWithData.push(slotWithData);
  });
  return {
    indexedTicTacToeSlotsWithData,
    recordOfTicTacToeSlotsWithDataAndIndex,
  };
};

const keysOfTicTacToeSlotsInOrder = [
  "northwest",
  "north",
  "northeast",
  "west",
  "center",
  "east",
  "southwest",
  "south",
  "southeast",
] as const satisfies KeysOfSlotsInOrder<RecordOfRequiredParamsOfTicTacToeSlots>;

const {
  indexedTicTacToeSlotsWithData:
    indexedTicTacToeSlotsWithDataInWhichAllSlotsAreEmpty,
  recordOfTicTacToeSlotsWithDataAndIndex:
    recordOfTicTacToeSlotsWithDataAndIndexInWhichAllSlotsAreEmpty,
} = createIndexedTicTacToeSlotsWithData({
  keysOfTicTacToeSlotsInOrder,
  ticTacToeSlotsWithData: recordOfTicTacToeSlotsWithDataInWhichAllSlotsAreEmpty,
});

const {
  indexedTicTacToeSlotsWithData:
    indexedTicTacToeSlotsWithDataInWhichSlotR0C0IsFilledByAlice,
  recordOfTicTacToeSlotsWithDataAndIndex:
    recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotR0C0IsFilledByAlice,
} = createIndexedTicTacToeSlotsWithData({
  keysOfTicTacToeSlotsInOrder,
  ticTacToeSlotsWithData:
    recordOfTicTacToeSlotsWithDataInWhichSlotR0C0IsFilledByAlice,
});

const {
  indexedTicTacToeSlotsWithData:
    indexedTicTacToeSlotsWithDataInWhichSlotR0C1IsFilledByAlice,
  recordOfTicTacToeSlotsWithDataAndIndex:
    recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotR0C1IsFilledByAlice,
} = createIndexedTicTacToeSlotsWithData({
  keysOfTicTacToeSlotsInOrder,
  ticTacToeSlotsWithData:
    recordOfTicTacToeSlotsWithDataInWhichSlotR0C1IsFilledByAlice,
});

const {
  indexedTicTacToeSlotsWithData:
    indexedTicTacToeSlotsWithDataInWhichSlotR0C2IsFilledByAlice,
  recordOfTicTacToeSlotsWithDataAndIndex:
    recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotR0C2IsFilledByAlice,
} = createIndexedTicTacToeSlotsWithData({
  keysOfTicTacToeSlotsInOrder,
  ticTacToeSlotsWithData:
    recordOfTicTacToeSlotsWithDataInWhichSlotR0C2IsFilledByAlice,
});

const {
  indexedTicTacToeSlotsWithData:
    indexedTicTacToeSlotsWithDataInWhichSlotR1C0IsFilledByAlice,
  recordOfTicTacToeSlotsWithDataAndIndex:
    recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotR1C0IsFilledByAlice,
} = createIndexedTicTacToeSlotsWithData({
  keysOfTicTacToeSlotsInOrder,
  ticTacToeSlotsWithData:
    recordOfTicTacToeSlotsWithDataInWhichSlotR1C0IsFilledByAlice,
});

const {
  indexedTicTacToeSlotsWithData:
    indexedTicTacToeSlotsWithDataInWhichSlotR1C1IsFilledByAlice,
  recordOfTicTacToeSlotsWithDataAndIndex:
    recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotR1C1IsFilledByAlice,
} = createIndexedTicTacToeSlotsWithData({
  keysOfTicTacToeSlotsInOrder,
  ticTacToeSlotsWithData:
    recordOfTicTacToeSlotsWithDataInWhichSlotR1C1IsFilledByAlice,
});

const {
  indexedTicTacToeSlotsWithData:
    indexedTicTacToeSlotsWithDataInWhichSlotR1C2IsFilledByAlice,
  recordOfTicTacToeSlotsWithDataAndIndex:
    recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotR1C2IsFilledByAlice,
} = createIndexedTicTacToeSlotsWithData({
  keysOfTicTacToeSlotsInOrder,
  ticTacToeSlotsWithData:
    recordOfTicTacToeSlotsWithDataInWhichSlotR1C2IsFilledByAlice,
});

const {
  indexedTicTacToeSlotsWithData:
    indexedTicTacToeSlotsWithDataInWhichSlotR2C0IsFilledByAlice,
  recordOfTicTacToeSlotsWithDataAndIndex:
    recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotR2C0IsFilledByAlice,
} = createIndexedTicTacToeSlotsWithData({
  keysOfTicTacToeSlotsInOrder,
  ticTacToeSlotsWithData:
    recordOfTicTacToeSlotsWithDataInWhichSlotR2C0IsFilledByAlice,
});

const {
  indexedTicTacToeSlotsWithData:
    indexedTicTacToeSlotsWithDataInWhichSlotR2C1IsFilledByAlice,
  recordOfTicTacToeSlotsWithDataAndIndex:
    recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotR2C1IsFilledByAlice,
} = createIndexedTicTacToeSlotsWithData({
  keysOfTicTacToeSlotsInOrder,
  ticTacToeSlotsWithData:
    recordOfTicTacToeSlotsWithDataInWhichSlotR2C1IsFilledByAlice,
});

const {
  indexedTicTacToeSlotsWithData:
    indexedTicTacToeSlotsWithDataInWhichSlotR2C2IsFilledByAlice,
  recordOfTicTacToeSlotsWithDataAndIndex:
    recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotR2C2IsFilledByAlice,
} = createIndexedTicTacToeSlotsWithData({
  keysOfTicTacToeSlotsInOrder,
  ticTacToeSlotsWithData:
    recordOfTicTacToeSlotsWithDataInWhichSlotR2C2IsFilledByAlice,
});

const {
  indexedTicTacToeSlotsWithData:
    indexedTicTacToeSlotsWithDataInWhichSlotsR0C0AndR0C1AndR1C0AreFilledByAliceAndR0C2AndR1C1AreFilledByBruno,
  recordOfTicTacToeSlotsWithDataAndIndex:
    recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotsR0C0AndR0C1AndR1C0AreFilledByAliceAndR0C2AndR1C1AreFilledByBruno,
} = createIndexedTicTacToeSlotsWithData({
  keysOfTicTacToeSlotsInOrder,
  ticTacToeSlotsWithData:
    recordOfTicTacToeSlotsWithDataInWhichSlotsR0C0AndR0C1AndR1C0AreFilledByAliceAndR0C2AndR1C1AreFilledByBruno,
});

const {
  indexedTicTacToeSlotsWithData:
    indexedTicTacToeSlotsWithDataInWhichSlotsR0C0AndR0C1AndR1C2AndR2C0AreFilledByAliceAndR0C2AndR1C0AndR1C1AreFilledByBruno,
  recordOfTicTacToeSlotsWithDataAndIndex:
    recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotsR0C0AndR0C1AndR1C2AndR2C0AreFilledByAliceAndR0C2AndR1C0AndR1C1AreFilledByBruno,
} = createIndexedTicTacToeSlotsWithData({
  keysOfTicTacToeSlotsInOrder,
  ticTacToeSlotsWithData:
    recordOfTicTacToeSlotsWithDataInWhichSlotsR0C0AndR0C1AndR1C2AndR2C0AreFilledByAliceAndR0C2AndR1C0AndR1C1AreFilledByBruno,
});

const {
  indexedTicTacToeSlotsWithData:
    indexedTicTacToeSlotsWithDataInWhichSlotsR0C0AndR0C1AreFilledByAliceAndR1C1IsFilledByBruno,
  recordOfTicTacToeSlotsWithDataAndIndex:
    recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotsR0C0AndR0C1AreFilledByAliceAndR1C1IsFilledByBruno,
} = createIndexedTicTacToeSlotsWithData({
  keysOfTicTacToeSlotsInOrder,
  ticTacToeSlotsWithData:
    recordOfTicTacToeSlotsWithDataInWhichSlotsR0C0AndR0C1AreFilledByAliceAndR1C1IsFilledByBruno,
});

const {
  indexedTicTacToeSlotsWithData:
    indexedTicTacToeSlotsWithDataInWhichSlotsR0C0AndR0C1AreFilledByAliceAndR2C0IsFilledByBruno,
  recordOfTicTacToeSlotsWithDataAndIndex:
    recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotsR0C0AndR0C1AreFilledByAliceAndR2C0IsFilledByBruno,
} = createIndexedTicTacToeSlotsWithData({
  keysOfTicTacToeSlotsInOrder,
  ticTacToeSlotsWithData:
    recordOfTicTacToeSlotsWithDataInWhichSlotsR0C0AndR0C1AreFilledByAliceAndR2C0IsFilledByBruno,
});

const {
  indexedTicTacToeSlotsWithData:
    indexedTicTacToeSlotsWithDataInWhichSlotsR0C0AndR0C2AndR1C1AndR1C2AndR2C1AreFilledByAliceAndR0C1AndR1C0AndR2C0AndR2C2AreFilledByBruno,
  recordOfTicTacToeSlotsWithDataAndIndex:
    recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotsR0C0AndR0C2AndR1C1AndR1C2AndR2C1AreFilledByAliceAndR0C1AndR1C0AndR2C0AndR2C2AreFilledByBruno,
} = createIndexedTicTacToeSlotsWithData({
  keysOfTicTacToeSlotsInOrder,
  ticTacToeSlotsWithData:
    recordOfTicTacToeSlotsWithDataInWhichSlotsR0C0AndR0C2AndR1C1AndR1C2AndR2C1AreFilledByAliceAndR0C1AndR1C0AndR2C0AndR2C2AreFilledByBruno,
});

const {
  indexedTicTacToeSlotsWithData:
    indexedTicTacToeSlotsWithDataInWhichSlotsR0C0AndR0C2AndR1C1AndR2C1AndR2C2AreFilledByAliceAndR0C1AndR1C0AndR1C2AndR2C0AreFilledByBruno,
  recordOfTicTacToeSlotsWithDataAndIndex:
    recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotsR0C0AndR0C2AndR1C1AndR2C1AndR2C2AreFilledByAliceAndR0C1AndR1C0AndR1C2AndR2C0AreFilledByBruno,
} = createIndexedTicTacToeSlotsWithData({
  keysOfTicTacToeSlotsInOrder,
  ticTacToeSlotsWithData:
    recordOfTicTacToeSlotsWithDataInWhichSlotsR0C0AndR0C2AndR1C1AndR2C1AndR2C2AreFilledByAliceAndR0C1AndR1C0AndR1C2AndR2C0AreFilledByBruno,
});

const {
  indexedTicTacToeSlotsWithData:
    indexedTicTacToeSlotsWithDataInWhichSlotsR0C0AndR0C2AndR1C1AndR2C1AreFilledByAliceAndR0C1AndR1C0AndR1C2AndR2C0AreFilledByBruno,
  recordOfTicTacToeSlotsWithDataAndIndex:
    recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotsR0C0AndR0C2AndR1C1AndR2C1AreFilledByAliceAndR0C1AndR1C0AndR1C2AndR2C0AreFilledByBruno,
} = createIndexedTicTacToeSlotsWithData({
  keysOfTicTacToeSlotsInOrder,
  ticTacToeSlotsWithData:
    recordOfTicTacToeSlotsWithDataInWhichSlotsR0C0AndR0C2AndR1C1AndR2C1AreFilledByAliceAndR0C1AndR1C0AndR1C2AndR2C0AreFilledByBruno,
});

const {
  indexedTicTacToeSlotsWithData:
    indexedTicTacToeSlotsWithDataInWhichSlotsR0C0AndR1C0AreFilledByAliceAndR0C1IsFilledByBruno,
  recordOfTicTacToeSlotsWithDataAndIndex:
    recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotsR0C0AndR1C0AreFilledByAliceAndR0C1IsFilledByBruno,
} = createIndexedTicTacToeSlotsWithData({
  keysOfTicTacToeSlotsInOrder,
  ticTacToeSlotsWithData:
    recordOfTicTacToeSlotsWithDataInWhichSlotsR0C0AndR1C0AreFilledByAliceAndR0C1IsFilledByBruno,
});

const {
  indexedTicTacToeSlotsWithData:
    indexedTicTacToeSlotsWithDataInWhichSlotsR1C0AndR1C2AndR2C0AreFilledByAliceAndR0C0AndR1C1AreFilledByBruno,
  recordOfTicTacToeSlotsWithDataAndIndex:
    recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotsR1C0AndR1C2AndR2C0AreFilledByAliceAndR0C0AndR1C1AreFilledByBruno,
} = createIndexedTicTacToeSlotsWithData({
  keysOfTicTacToeSlotsInOrder,
  ticTacToeSlotsWithData:
    recordOfTicTacToeSlotsWithDataInWhichSlotsR1C0AndR1C2AndR2C0AreFilledByAliceAndR0C0AndR1C1AreFilledByBruno,
});

export type { TicTacToeSlotWithDataAndIndex };
export {
  indexedTicTacToeSlotsWithDataInWhichAllSlotsAreEmpty,
  indexedTicTacToeSlotsWithDataInWhichSlotR0C0IsFilledByAlice,
  indexedTicTacToeSlotsWithDataInWhichSlotR0C1IsFilledByAlice,
  indexedTicTacToeSlotsWithDataInWhichSlotR0C2IsFilledByAlice,
  indexedTicTacToeSlotsWithDataInWhichSlotR1C0IsFilledByAlice,
  indexedTicTacToeSlotsWithDataInWhichSlotR1C1IsFilledByAlice,
  indexedTicTacToeSlotsWithDataInWhichSlotR1C2IsFilledByAlice,
  indexedTicTacToeSlotsWithDataInWhichSlotR2C0IsFilledByAlice,
  indexedTicTacToeSlotsWithDataInWhichSlotR2C1IsFilledByAlice,
  indexedTicTacToeSlotsWithDataInWhichSlotR2C2IsFilledByAlice,
  indexedTicTacToeSlotsWithDataInWhichSlotsR0C0AndR0C1AndR1C0AreFilledByAliceAndR0C2AndR1C1AreFilledByBruno,
  indexedTicTacToeSlotsWithDataInWhichSlotsR0C0AndR0C1AndR1C2AndR2C0AreFilledByAliceAndR0C2AndR1C0AndR1C1AreFilledByBruno,
  indexedTicTacToeSlotsWithDataInWhichSlotsR0C0AndR0C1AreFilledByAliceAndR1C1IsFilledByBruno,
  indexedTicTacToeSlotsWithDataInWhichSlotsR0C0AndR0C1AreFilledByAliceAndR2C0IsFilledByBruno,
  indexedTicTacToeSlotsWithDataInWhichSlotsR0C0AndR0C2AndR1C1AndR1C2AndR2C1AreFilledByAliceAndR0C1AndR1C0AndR2C0AndR2C2AreFilledByBruno,
  indexedTicTacToeSlotsWithDataInWhichSlotsR0C0AndR0C2AndR1C1AndR2C1AndR2C2AreFilledByAliceAndR0C1AndR1C0AndR1C2AndR2C0AreFilledByBruno,
  indexedTicTacToeSlotsWithDataInWhichSlotsR0C0AndR0C2AndR1C1AndR2C1AreFilledByAliceAndR0C1AndR1C0AndR1C2AndR2C0AreFilledByBruno,
  indexedTicTacToeSlotsWithDataInWhichSlotsR0C0AndR1C0AreFilledByAliceAndR0C1IsFilledByBruno,
  indexedTicTacToeSlotsWithDataInWhichSlotsR1C0AndR1C2AndR2C0AreFilledByAliceAndR0C0AndR1C1AreFilledByBruno,
  recordOfTicTacToeSlotsWithDataAndIndexInWhichAllSlotsAreEmpty,
  recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotR0C0IsFilledByAlice,
  recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotR0C1IsFilledByAlice,
  recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotR0C2IsFilledByAlice,
  recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotR1C0IsFilledByAlice,
  recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotR1C1IsFilledByAlice,
  recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotR1C2IsFilledByAlice,
  recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotR2C0IsFilledByAlice,
  recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotR2C1IsFilledByAlice,
  recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotR2C2IsFilledByAlice,
  recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotsR0C0AndR0C1AndR1C0AreFilledByAliceAndR0C2AndR1C1AreFilledByBruno,
  recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotsR0C0AndR0C1AndR1C2AndR2C0AreFilledByAliceAndR0C2AndR1C0AndR1C1AreFilledByBruno,
  recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotsR0C0AndR0C1AreFilledByAliceAndR1C1IsFilledByBruno,
  recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotsR0C0AndR0C1AreFilledByAliceAndR2C0IsFilledByBruno,
  recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotsR0C0AndR0C2AndR1C1AndR1C2AndR2C1AreFilledByAliceAndR0C1AndR1C0AndR2C0AndR2C2AreFilledByBruno,
  recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotsR0C0AndR0C2AndR1C1AndR2C1AndR2C2AreFilledByAliceAndR0C1AndR1C0AndR1C2AndR2C0AreFilledByBruno,
  recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotsR0C0AndR0C2AndR1C1AndR2C1AreFilledByAliceAndR0C1AndR1C0AndR1C2AndR2C0AreFilledByBruno,
  recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotsR0C0AndR1C0AreFilledByAliceAndR0C1IsFilledByBruno,
  recordOfTicTacToeSlotsWithDataAndIndexInWhichSlotsR1C0AndR1C2AndR2C0AreFilledByAliceAndR0C0AndR1C1AreFilledByBruno,
};
