const FIRST_INDEX = 0;

const LENGTH_OF_EMPTY_LIST = 0;
const SIZE_OF_EMPTY_SET = 0;

const NOT_INCREMENT = 0;
const INCREMENT_ONE = 1;

export {
  FIRST_INDEX,
  INCREMENT_ONE,
  LENGTH_OF_EMPTY_LIST,
  NOT_INCREMENT,
  SIZE_OF_EMPTY_SET,
};
