import { recordOfSnowballGamesWithData } from "../Game.test/records.js";
import {
  recordOfSnowballMovesWithDataAndIndex,
  type SnowballMoveWithDataAndIndex,
} from "../Move.test/indexedRecords.js";
import { type SnowballMoveWithData } from "../Move.test/setup.js";
import { playersWithDataAndIndexInWhichThereAreAliceWithSymbolXAndBrunoWithSymbolO as playersWithDataAndIndex } from "../Player.test/indexedRecords.js";
import { scoresWithData } from "../Score.test/records.js";
import {
  indexedSlotsWithDataInWhichAllSlotsAreEmpty,
  indexedSlotsWithDataInWhichSlotR0C0IsFilledByAlice,
  indexedSlotsWithDataInWhichSlotsR0C0ToR3C3AndR4C0AndR4C2AreFilledByAliceAndSlotsR0C4ToR3C7AndR3C8AreFilledByBruno,
  indexedSlotsWithDataInWhichSlotsR0C0ToR3C3AndR4C0AreFilledByAliceAndSlotsR0C4ToR3C7AndR3C8AreFilledByBruno,
  indexedSlotsWithDataInWhichSlotsR0C0ToR4C4AndR5C5AreFilledByAliceAndSlotsR8C4AndR6C5ToR8C6AndR0C7ToR8C8AreFilledByBruno,
} from "../Slot.test/indexedRecords.js";
import {
  createSnowballStatesWithData,
  type RequiredParamsOfSnowballState,
} from "./setup.js";

type RecordOfRequiredParamsOfSnowballStates = Record<
  string,
  RequiredParamsOfSnowballState
>;

const constructTupleForMove = ({
  moveWithDataAndIndex,
}: {
  moveWithDataAndIndex: SnowballMoveWithDataAndIndex;
}): [number, SnowballMoveWithData] => [
  moveWithDataAndIndex.indexOfMove,
  moveWithDataAndIndex.moveWithData,
];

const recordOfRequiredParamsOfStates = {
  allSlotsAreEmptyAndAliceHas0PointsAndBrunoHas0PointsAndAliceIsTheCurrentPlayer:
    {
      game: recordOfSnowballGamesWithData.snowballWith9RowsAnd9Columns,
      isFinal: false,
      nextPlayer: playersWithDataAndIndex.bruno,
      player: playersWithDataAndIndex.alice,
      score: scoresWithData.aliceWith0PointsAndBrunoWith0Points,
      slots: indexedSlotsWithDataInWhichAllSlotsAreEmpty,
      validMoves: new Map([
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfWest,
        }),
      ]),
    },
  slotR0C0IsFilledByAliceAndAliceHas0PointsAndBrunoHas0PointsAndBrunoIsTheCurrentPlayer:
    {
      game: recordOfSnowballGamesWithData.snowballWith9RowsAnd9Columns,
      isFinal: false,
      nextPlayer: playersWithDataAndIndex.alice,
      player: playersWithDataAndIndex.bruno,
      score: scoresWithData.aliceWith0PointsAndBrunoWith0Points,
      slots: indexedSlotsWithDataInWhichSlotR0C0IsFilledByAlice,
      validMoves: new Map([
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfNorthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfWest,
        }),
      ]),
    },
  slotsR0C0ToR3C3AndR4C0AndR4C2AreFilledByAliceAndSlotsR0C4ToR3C7AndR3C8AreFilledByBrunoAndAliceHas0PointsAndBrunoHas0PointsAndBrunoIsTheCurrentPlayer:
    {
      game: recordOfSnowballGamesWithData.snowballWith9RowsAnd9Columns,
      isFinal: true,
      nextPlayer: playersWithDataAndIndex.alice,
      player: playersWithDataAndIndex.bruno,
      score: scoresWithData.aliceWith15PointsAndBrunoWith14Points,
      slots:
        indexedSlotsWithDataInWhichSlotsR0C0ToR3C3AndR4C0AndR4C2AreFilledByAliceAndSlotsR0C4ToR3C7AndR3C8AreFilledByBruno,
      validMoves: new Map([
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfSouthwest,
        }),
      ]),
    },
  slotsR0C0ToR3C3AndR4C0AreFilledByAliceAndSlotsR0C4ToR3C7AndR3C8AreFilledByBrunoAndAliceHas0PointsAndBrunoHas0PointsAndAliceIsTheCurrentPlayer:
    {
      game: recordOfSnowballGamesWithData.snowballWith9RowsAnd9Columns,
      isFinal: false,
      nextPlayer: playersWithDataAndIndex.bruno,
      player: playersWithDataAndIndex.alice,
      score: scoresWithData.aliceWith14PointsAndBrunoWith14Points,
      slots:
        indexedSlotsWithDataInWhichSlotsR0C0ToR3C3AndR4C0AreFilledByAliceAndSlotsR0C4ToR3C7AndR3C8AreFilledByBruno,
      validMoves: new Map([
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfSoutheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfSouthwest,
        }),
      ]),
    },
  slotsR0C0ToR4C4AndR5C5AreFilledByAliceAndSlotsR8C4AndR6C5ToR8C6AndR0C7ToR8C8AreFilledByBrunoAndAliceHas0PointsAndBrunoHas0PointsAndBrunoIsTheCurrentPlayer:
    {
      game: recordOfSnowballGamesWithData.snowballWith9RowsAnd9Columns,
      isFinal: true,
      nextPlayer: playersWithDataAndIndex.alice,
      player: playersWithDataAndIndex.bruno,
      score: scoresWithData.aliceWith38PointsAndBrunoWith26Points,
      slots:
        indexedSlotsWithDataInWhichSlotsR0C0ToR4C4AndR5C5AreFilledByAliceAndSlotsR8C4AndR6C5ToR8C6AndR0C7ToR8C8AreFilledByBruno,
      validMoves: new Map([
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.centerOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.eastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northeastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.northwestOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfNorth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southeastOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfCenter,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfSouthwest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.southwestOfWest,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfEast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfNortheast,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfSouth,
        }),
        constructTupleForMove({
          moveWithDataAndIndex:
            recordOfSnowballMovesWithDataAndIndex.westOfSouthwest,
        }),
      ]),
    },
} as const satisfies RecordOfRequiredParamsOfSnowballStates;

const statesWithData = createSnowballStatesWithData({
  recordOfRequiredParams: recordOfRequiredParamsOfStates,
});

export type { RecordOfRequiredParamsOfSnowballStates };
export { recordOfRequiredParamsOfStates, statesWithData };
