@startuml modules_diagram

' left to right direction
skinparam linetype ortho
skinparam componentStyle rectangle
skinparam packageStyle rectangle
skinparam defaultFontName "Atkinson Hyperlegible Next"

package external{
  component "ts-graphviz"
  component tensorflow
}
"ts-graphviz" -[hidden]- tensorflow

component core
component game
component search
component games
component interface

game -up-> core

games -up-> core
games -up-> game
games -left-> search

search -up-> core
search -up-> game
search -left-> tensorflow

interface -up-> core
interface -up-> game
interface -left-> search
interface -left-> "ts-graphviz"
